---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hairyhenderson/gomplate
    tag: alpine
inputs:
  - name: paasify-pipelines-pas
  - name: terraform-state
outputs:
  - name: interpolated-templates
run:
  path: paasify-pipelines-pas/tasks/interpolate.sh