---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.9

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: semver-config
  type: docker-image
  source:
    repository: itstarting/semver-config-concourse-resource
    tag: 1.0.0

resources:
- name: terraform-state
  type: terraform
  source:
    backend_type: s3
    backend_config:
      bucket: ((s3_artifact_bucket))
      key: ((foundation))/terraform.tfstate
      endpoint: ((s3_endpoint))
      access_key: ((s3_access_key_id))
      secret_key: ((s3_secret_access_key))
    vars:
      env_name: ((foundation))
      dns_suffix: ((dns_suffix))
      region: ((region))
    env:
      AWS_ACCESS_KEY_ID: ((admin_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((admin_secret_access_key))
      AWS_DEFAULT_REGION: ((region))

- name: pipelines-source
  type: git
  source:
    uri: git@github.com:nthomson-pivotal/paasify-pipelines-pas.git
    branch: master

jobs:
- name: terraform
  serial: true
  public: false
  plan:
    - get: pipelines-source
    - put: terraform-state
      params:
        env_name: ((env_name))
        terraform_source: pipelines-source/terraform/aws
        delete_on_failure: false