---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.9

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: semver-config
  type: docker-image
  source:
    repository: itstarting/semver-config-concourse-resource
    tag: 1.0.0

resources:
- name: terraform-state
  type: terraform
  source:
    backend_type: s3
    backend_config:
      bucket: ((s3_artifact_bucket))
      key: ((env_name))/terraform.tfstate
      access_key: ((s3_access_key_id))
      secret_key: ((s3_secret_access_key))
    vars:
      env_name: ((env_name))
      dns_suffix: ((dns_suffix))
      region: ((region))
      ops_manager_ami: ""
    env:
      AWS_ACCESS_KEY_ID: ((admin_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((admin_secret_access_key))
      AWS_DEFAULT_REGION: ((region))

- name: pipelines-source
  type: git
  source:
    uri: https://github.com/nthomson-pivotal/paasify-pipelines-pas.git
    branch: master

- name: configuration-source
  type: git
  source:
    uri: ((configuration_source))
    branch: master

- name: product-config-opsman
  type: semver-config
  source:
    driver: git
    uri: ((configuration_source))
    branch: master
    config_file: ((env_name))/products.yml
    config_path: products.opsman
    version_path: products.opsman.product-version
    version_pattern: "m.n.p"

- name: platform-automation-tasks
  type: s3
  source:
    region_name: ((s3_region))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    bucket: ((s3_artifact_bucket))
    regexp: .*tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    region_name: ((s3_region))
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    bucket: ((s3_artifact_bucket))
    regexp: .*image-(.*).tgz

jobs:
- name: terraform
  serial: true
  public: false
  plan:
    - get: pipelines-source
    - get: configuration-source
      trigger: true
    - put: terraform-state
      params:
        env_name: ((env_name))
        terraform_source: pipelines-source/terraform/aws
        delete_on_failure: false
        var_files:
        - configuration-source/((env_name))/terraform.tfvars

- name: create-opsman-and-configure-auth
  serial: true
  plan:
  - aggregate:
    - get: pipelines-source
    - get: product-config-opsman
    - get: platform-automation-tasks
      params: {unpack: true}
    - get: platform-automation-image
      params: {unpack: true}
    - get: terraform-state
      trigger: true
      passed: [terraform]
#  - task: interpolate-config
#    file: pipelines-source/tasks/interpolate.yml
#    input_mapping:
#      paasify-pipelines-pas: pipelines-source
#      templates: product-config-opsman
#      terraform-state: terraform-state
#    output_mapping:
#      interpolated-templates: opsman-interpolated
#    params:
#      AWS_ACCESS_KEY_ID: ((admin_access_key_id))
#      AWS_SECRET_ACCESS_KEY: ((admin_secret_access_key))
  - task: interpolate-vars
    file: pipelines-source/tasks/interpolate.yml
    input_mapping:
      paasify-pipelines-pas: pipelines-source
      templates: pipelines-source
      terraform-state: terraform-state
    output_mapping:
      interpolated-templates: vars-interpolated
    params:
      TEMPLATE_PATH: products/opsman/vars
      PIVNET_TOKEN: ((pivnet_token))
      AWS_ACCESS_KEY_ID: ((admin_access_key_id))
      AWS_SECRET_ACCESS_KEY: ((admin_secret_access_key))
  - task: download-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: product-config-opsman
      vars: vars-interpolated
    params:
      CONFIG_FILE: semver-config.yaml
      VARS_FILES: vars/vars.yml
  - task: create-vm
    image: platform-automation-image
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      image: downloaded-product
      state: configuration
      config: pipelines-source
      vars: interpolated-files
    params:
      OPSMAN_CONFIG_FILE: pipelines/opsman/config/opsman.yml
      STATE_FILE: ((env_name))/state/state.yml