product-name: p-redis
product-properties:
  .properties.syslog_selector:
    value: 'No'
  .properties.small_plan_selector.active.az_multi_select:
    value:
    {{range (ds "data").azs}}
    - {{.}}
    {{end}}
  .properties.medium_plan_selector.active.az_multi_select:
    value:
    {{range (ds "data").azs}}
    - {{.}}
    {{end}}
  .properties.large_plan_selector.active.az_multi_select:
    value:
    {{range (ds "data").azs}}
    - {{.}}
    {{end}}
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones:
    {{range (ds "data").azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index (ds "data").azs 0}}